# Generated by Django 3.0.3 on 2020-05-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('classyear', models.CharField(max_length=200)),
                ('major', models.CharField(max_length=200)),
            ],
        ),
    ]
