# Generated by Django 2.0.1 on 2018-04-05 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=1)),
                ('longname', models.CharField(max_length=50)),
                ('regiment', models.IntegerField()),
                ('motto', models.CharField(max_length=100)),
                ('mascot', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cadet',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Company'),
        ),
    ]
