# Generated by Django 3.0.3 on 2020-05-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180405_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadet',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
