# Generated by Django 3.0.3 on 2020-05-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codhc', '0002_auto_20200508_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
